application: your-app-id
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: favicon.ico
  upload: favicon.ico

- url: .*
  script: main.php